elastic-query-service:
  backPressure-delay-ms: 500

server:
  port: 8183

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092   #, localhost:39092
  schema-registry-servers: http://localhost:8081
  topic-name: twitter-analytics-topic-2
  topic-names-to-create:
    - twitter-analytics-topic-2
  num-partitions: 3
  replication-factor: 2
  sleep-time-ms: 1000
  max-interval-ms: 10000
  retry-multiplier: 2.0
  admin-retry-max: 1

spring:
  webflux:
    base-path: /reactive-elastic-query-service
  codec:
    max-in-memory-size: 25MB
  data:
    elasticsearch:
      client:
        reactive:
          max-in-memory-size: 25MB